use_frameworks!

target 'SwiftySoundRecorder_Example' do
  pod 'SwiftySoundRecorder', :path => '../'
  pod 'SCSiriWaveformView'
  pod 'FDWaveformViewForked'
  #pod 'FDWaveformView'#, :git => 'https://github.com/hackiftekhar/FDWaveformView.git', :commit => '65369f6729bec964db984b7f7439a915342237de'
  

  target 'SwiftySoundRecorder_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
